### ISSUE TITLE
How to create wind data style

### ISSUE THREAD

**Issue by Ants-double** [kobeCan/cesium-wind#2]
can you give me the data rule.

**Comment by kobeCan** [comment]
**data/uvwind_d01.json** 
json数据是一个数组，第一个数据是X方向格点的风速，第二个数据是Y方向格点的风速，整个风场数据**145*139**，每个data都有个header头信息，风场边界经纬度，每个格网XY间距都有的

**Comment by cicici111** [comment]
那是不是说程序只用到了data里的uvwind_d01.json，其他json数据并没有用到？Emm，header头信息怎么看呀？
